In [61]:
import pandas as pd

df = pd.read_csv("spacex_data.csv")
df.shape

(205, 43)

In [62]:
df

,static_fire_date_utc,static_fire_date_unix,net,window,rocket,success,failures,details,crew,ships,...,links.reddit.media,links.reddit.recovery,links.flickr.small,links.flickr.original,links.presskit,links.webcast,links.youtube_id,links.article,links.wikipedia,fairings
0,2006-03-17T00:00:00.000Z,1.142554e+09,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",Engine failure at 33 seconds and loss of vehicle,[],[],...,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=0a_00nJ_Y88,0a_00nJ_Y88,https://www.space.com/2196-spacex-inaugural-fa...,https://en.wikipedia.org/wiki/DemoSat,NaN
1,NaN,NaN,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",Successful first stage burn and transition to ...,[],[],...,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=Lk4zQ2wP-Nc,Lk4zQ2wP-Nc,https://www.space.com/3590-spacex-falcon-1-roc...,https://en.wikipedia.org/wiki/DemoSat,NaN
2,NaN,NaN,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",Residual stage 1 thrust led to collision betwe...,[],[],...,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=v0w9p3U8860,v0w9p3U8860,http://www.spacex.com/news/2013/02/11/falcon-1...,https://en.wikipedia.org/wiki/Trailblazer_(sat...,NaN
3,2008-09-20T00:00:00.000Z,1.221869e+09,False,0.0,5e9d0d95eda69955f709d1eb,True,[],Ratsat was carried to orbit on the first succe...,[],[],...,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=dLQ2tZEH6G0,dLQ2tZEH6G0,https://en.wikipedia.org/wiki/Ratsat,https://en.wikipedia.org/wiki/Ratsat,NaN
4,NaN,NaN,False,0.0,5e9d0d95eda69955f709d1eb,True,[],NaN,[],[],...,NaN,NaN,[],[],http://www.spacex.com/press/2012/12/19/spacexs...,https://www.youtube.com/watch?v=yTaIDooc8Og,yTaIDooc8Og,http://www.spacex.com/news/2013/02/12/falcon-1...,https://en.wikipedia.org/wiki/RazakSAT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,NaN,NaN,False,NaN,5e9d0d95eda69973a809d1ec,NaN,[],NaN,[],[],...,NaN,NaN,[],[],NaN,NaN,NaN,NaN,NaN,NaN
201,NaN,NaN,False,NaN,5e9d0d95eda69974db09d1ed,NaN,[],NaN,[],[],...,NaN,NaN,[],[],NaN,NaN,NaN,NaN,NaN,NaN
202,NaN,NaN,False,NaN,5e9d0d95eda69973a809d1ec,NaN,[],NaN,[],[],...,NaN,NaN,[],[],NaN,NaN,NaN,NaN,NaN,NaN
203,NaN,NaN,False,NaN,5e9d0d95eda69973a809d1ec,NaN,[],NaN,[],[],...,NaN,NaN,[],[],NaN,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,False,NaN,5e9d0d95eda69973a809d1ec,NaN,[],NaN,[],[],...,NaN,NaN,[],[],NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
df.head()

,static_fire_date_utc,static_fire_date_unix,net,window,rocket,success,failures,details,crew,ships,...,links.reddit.media,links.reddit.recovery,links.flickr.small,links.flickr.original,links.presskit,links.webcast,links.youtube_id,links.article,links.wikipedia,fairings
0,2006-03-17T00:00:00.000Z,1.142554e+09,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",Engine failure at 33 seconds and loss of vehicle,[],[],...,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=0a_00nJ_Y88,0a_00nJ_Y88,https://www.space.com/2196-spacex-inaugural-fa...,https://en.wikipedia.org/wiki/DemoSat,NaN
1,NaN,NaN,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",Successful first stage burn and transition to ...,[],[],...,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=Lk4zQ2wP-Nc,Lk4zQ2wP-Nc,https://www.space.com/3590-spacex-falcon-1-roc...,https://en.wikipedia.org/wiki/DemoSat,NaN
2,NaN,NaN,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",Residual stage 1 thrust led to collision betwe...,[],[],...,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=v0w9p3U8860,v0w9p3U8860,http://www.spacex.com/news/2013/02/11/falcon-1...,https://en.wikipedia.org/wiki/Trailblazer_(sat...,NaN
3,2008-09-20T00:00:00.000Z,1.221869e+09,False,0.0,5e9d0d95eda69955f709d1eb,True,[],Ratsat was carried to orbit on the first succe...,[],[],...,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=dLQ2tZEH6G0,dLQ2tZEH6G0,https://en.wikipedia.org/wiki/Ratsat,https://en.wikipedia.org/wiki/Ratsat,NaN
4,NaN,NaN,False,0.0,5e9d0d95eda69955f709d1eb,True,[],NaN,[],[],...,NaN,NaN,[],[],http://www.spacex.com/press/2012/12/19/spacexs...,https://www.youtube.com/watch?v=yTaIDooc8Og,yTaIDooc8Og,http://www.spacex.com/news/2013/02/12/falcon-1...,https://en.wikipedia.org/wiki/RazakSAT,NaN

In [64]:
df[['name', 'date_utc', 'success', 'rocket', 'launchpad', 'payloads']].head()

,name,date_utc,success,rocket,launchpad,payloads
0,FalconSat,2006-03-24T22:30:00.000Z,False,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b5b6c3bb0006eeb1e1']
1,DemoSat,2007-03-21T01:10:00.000Z,False,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b6b6c3bb0006eeb1e2']
2,Trailblazer,2008-08-03T03:34:00.000Z,False,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,"['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00..."
3,RatSat,2008-09-28T23:15:00.000Z,True,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e5']
4,RazakSat,2009-07-13T03:35:00.000Z,True,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e6']

In [65]:
df.isna().sum()

static_fire_date_utc          84
static_fire_date_unix         84
net                            0
window                        88
rocket                         0
success                       19
failures                       0
details                       71
crew                           0
ships                          0
capsules                       0
payloads                       0
launchpad                      0
flight_number                  0
name                           0
date_utc                       0
date_unix                      0
date_local                     0
date_precision                 0
upcoming                       0
cores                          0
auto_update                    0
tbd                            0
launch_library_id            133
id                             0
fairings.reused              112
fairings.recovery_attempt     98
fairings.recovered           120
fairings.ships                36
links.patch.small             16
links.patch.large             16
links.reddit.campaign         55
links.reddit.launch           41
links.reddit.media           117
links.reddit.recovery        110
links.flickr.small             0
links.flickr.original          0
links.presskit               114
links.webcast                 17
links.youtube_id              17
links.article                 63
links.wikipedia               50
fairings                     205
dtype: int64

DROPING UNNECESSARY COLUMNS

In [66]:
df.cores.value_counts()

cores
[{'core': None, 'flight': None, 'gridfins': True, 'legs': True, 'reused': False, 'landing_attempt': None, 'landing_success': None, 'landing_type': None, 'landpad': None}]                                                                                                                                                                                                                                                                                                                                                        10
[{'core': None, 'flight': None, 'gridfins': None, 'legs': None, 'reused': None, 'landing_attempt': None, 'landing_success': None, 'landing_type': None, 'landpad': None}]                                                                                                                                                                                                                                                                                                                                                          6
[{'core': '5e9e289df35918033d3b2623', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]                                                                                                                                                                                                                                                                                                                                   1
[{'core': '5e9e289ef3591855dc3b2626', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]                                                                                                                                                                                                                                                                                                                                   1
[{'core': '5e9e289ef359184f103b2627', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]                                                                                                                                                                                                                                                                                                                                   1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ..
[{'core': '61c1ef45a4a2462678cbf45d', 'flight': 2, 'gridfins': True, 'legs': True, 'reused': True, 'landing_attempt': True, 'landing_success': True, 'landing_type': 'ASDS', 'landpad': '5e9e3033383ecb075134e7cd'}]                                                                                                                                                                                                                                                                                                               1
[{'core': '5f57c54a0622a633027900a1', 'flight': 7, 'gridfins': True, 'legs': True, 'reused': True, 'landing_attempt': True, 'landing_success': True, 'landing_type': 'ASDS', 'landpad': '5e9e3032383ecb6bb234e7ca'}]                                                                                                                                                                                                                                                                                                               1
[{'core': '60b800111f83cc1e59f16438', 'flight': 6, 'gridfins': True, 'legs': True, 'reused': True, 'landing_attempt': True, 'landing_success': True, 'landing_type': 'ASDS', 'landpad': '5e9e3033383ecbb9e534e7cc'}]                                                                                                                                                                                                                                                                                                               1
[{'core': '627843d657b51b752c5c5a53', 'flight': 4, 'gridfins': True, 'legs': True, 'reused': True, 'landing_attempt': True, 'landing_success': True, 'landing_type': 'ASDS', 'landpad': '5e9e3033383ecbb9e534e7cc'}]                                                                                                                                                                                                                                                                                                               1
[{'core': None, 'flight': None, 'gridfins': True, 'legs': True, 'reused': False, 'landing_attempt': None, 'landing_success': None, 'landing_type': None, 'landpad': None}, {'core': None, 'flight': None, 'gridfins': True, 'legs': True, 'reused': False, 'landing_attempt': None, 'landing_success': None, 'landing_type': None, 'landpad': None}, {'core': None, 'flight': None, 'gridfins': True, 'legs': True, 'reused': False, 'landing_attempt': None, 'landing_success': None, 'landing_type': None, 'landpad': None}]     1
Name: count, Length: 191, dtype: int64

COLOUMNS TO DROP
drop_cols = [
    'static_fire_date_utc', 'static_fire_date_unix', 'net', 'window',
    'details', 'crew', 'ships', 'capsules', 'launch_library_id', 'date_local',
    'date_unix', 'date_precision', 'auto_update', 'tbd', 'links.youtube_id',
    'links.article', 'links.wikipedia', 'fairings'
]

df = df.drop(columns=drop_cols, errors='ignore')

| Column             | Reason to Keep                                                                               |
| ------------------ | -------------------------------------------------------------------------------------------- |
| `rocket`           | Used to map rocket name (e.g., Falcon 9); rocket type may influence success.                 |
| `launchpad`        | Launch site (geographic & facility differences affect success).                              |
| `payloads`         | Use to extract payload type and mass, which are important for ML.                            |
| `date_utc`         | Allows extraction of time-based features (year, month, weekday, daylight).                   |
| `success`          | 🎯 Target variable for ML classification (success vs failure).                               |
| `name`             | May contain mission-specific keywords (e.g., "Starlink", "Crew") that help analysis.         |
| `flight_number`    | Can reflect organizational learning curve (e.g., newer missions tend to be more successful). |
| `upcoming`         | Used to filter future launches (only train on historical data).                              |
| `cores` (optional) | Advanced feature: Reuse of core stage, which may impact reliability/success.                 |

| Column                  | Reason to Drop                                                     |
| ----------------------- | ------------------------------------------------------------------ |
| `static_fire_date_utc`  | Often missing; adds limited predictive power.                      |
| `static_fire_date_unix` | Same as above; also redundant format.                              |
| `net`                   | Scheduling metadata; not predictive.                               |
| `window`                | Not informative without weather or time alignment.                 |
| `details`               | Unstructured free text, hard to use in ML.                         |
| `crew`                  | Only relevant for crewed flights (rare).                           |
| `ships`                 | Specific to maritime missions, not widely relevant.                |
| `capsules`              | Crew capsule data; limited use in general launches.                |
| `launch_library_id`     | External DB reference, irrelevant for prediction.                  |
| `date_local`            | Redundant with `date_utc`.                                         |
| `date_unix`             | Redundant time format.                                             |
| `date_precision`        | Precision of the date (e.g., exact or estimated) — not predictive. |
| `auto_update`           | Metadata flag; not meaningful for modeling.                        |
| `tbd`                   | "To be decided" flag; only applies to planning, not past data.     |
| `links.youtube_id`      | Link to media; not useful for analysis.                            |
| `links.article`         | Article URL; not useful for prediction.                            |
| `links.wikipedia`       | Wiki URL; not predictive.                                          |
| `fairings`              | Mostly null and inconsistent — minor influence on success.         |

In [67]:
# Step 1: Drop irrelevant columns
drop_cols = [
    'static_fire_date_utc', 'static_fire_date_unix', 'net', 'window',
    'details', 'crew', 'ships', 'capsules', 'launch_library_id', 'date_local',
    'date_unix', 'date_precision', 'auto_update', 'tbd', 'links.youtube_id',
    'links.article', 'links.wikipedia', 'fairings'
]

df = df.drop(columns=drop_cols, errors='ignore')

In [68]:
df

,rocket,success,failures,payloads,launchpad,flight_number,name,date_utc,upcoming,cores,...,links.patch.small,links.patch.large,links.reddit.campaign,links.reddit.launch,links.reddit.media,links.reddit.recovery,links.flickr.small,links.flickr.original,links.presskit,links.webcast
0,5e9d0d95eda69955f709d1eb,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",['5eb0e4b5b6c3bb0006eeb1e1'],5e9e4502f5090995de566f86,1,FalconSat,2006-03-24T22:30:00.000Z,False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",...,https://images2.imgbox.com/94/f2/NN6Ph45r_o.png,https://images2.imgbox.com/5b/02/QcxHUb5V_o.png,NaN,NaN,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=0a_00nJ_Y88
1,5e9d0d95eda69955f709d1eb,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",['5eb0e4b6b6c3bb0006eeb1e2'],5e9e4502f5090995de566f86,2,DemoSat,2007-03-21T01:10:00.000Z,False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",...,https://images2.imgbox.com/f9/4a/ZboXReNb_o.png,https://images2.imgbox.com/80/a2/bkWotCIS_o.png,NaN,NaN,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=Lk4zQ2wP-Nc
2,5e9d0d95eda69955f709d1eb,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...","['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",5e9e4502f5090995de566f86,3,Trailblazer,2008-08-03T03:34:00.000Z,False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",...,https://images2.imgbox.com/6c/cb/na1tzhHs_o.png,https://images2.imgbox.com/4a/80/k1oAkY0k_o.png,NaN,NaN,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=v0w9p3U8860
3,5e9d0d95eda69955f709d1eb,True,[],['5eb0e4b7b6c3bb0006eeb1e5'],5e9e4502f5090995de566f86,4,RatSat,2008-09-28T23:15:00.000Z,False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",...,https://images2.imgbox.com/95/39/sRqN7rsv_o.png,https://images2.imgbox.com/a3/99/qswRYzE8_o.png,NaN,NaN,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=dLQ2tZEH6G0
4,5e9d0d95eda69955f709d1eb,True,[],['5eb0e4b7b6c3bb0006eeb1e6'],5e9e4502f5090995de566f86,5,RazakSat,2009-07-13T03:35:00.000Z,False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",...,https://images2.imgbox.com/ab/5a/Pequxd5d_o.png,https://images2.imgbox.com/92/e4/7Cf6MLY0_o.png,NaN,NaN,NaN,NaN,[],[],http://www.spacex.com/press/2012/12/19/spacexs...,https://www.youtube.com/watch?v=yTaIDooc8Og
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,5e9d0d95eda69973a809d1ec,NaN,[],[],5e9e4501f509094ba4566f84,198,SES-18 & SES-19,2022-11-01T00:00:00.000Z,True,"[{'core': None, 'flight': None, 'gridfins': Tr...",...,NaN,NaN,NaN,NaN,NaN,NaN,[],[],NaN,NaN
201,5e9d0d95eda69974db09d1ed,NaN,[],[],5e9e4502f509094188566f88,202,Viasat-3 & Arcturus,2022-12-01T00:00:00.000Z,True,"[{'core': None, 'flight': None, 'gridfins': Tr...",...,NaN,NaN,NaN,NaN,NaN,NaN,[],[],NaN,NaN
202,5e9d0d95eda69973a809d1ec,NaN,[],[],5e9e4501f509094ba4566f84,193,ispace Mission 1 & Rashid,2022-11-22T00:00:00.000Z,True,"[{'core': None, 'flight': None, 'gridfins': Tr...",...,NaN,NaN,NaN,NaN,NaN,NaN,[],[],NaN,NaN
203,5e9d0d95eda69973a809d1ec,NaN,[],[],5e9e4502f509092b78566f87,197,SWOT,2022-12-05T00:00:00.000Z,True,"[{'core': None, 'flight': None, 'gridfins': Tr...",...,NaN,NaN,NaN,NaN,NaN,NaN,[],[],NaN,NaN
204,5e9d0d95eda69973a809d1ec,NaN,[],[],5e9e4501f509094ba4566f84,198,Transporter-6,2022-12-01T00:00:00.000Z,True,"[{'core': None, 'flight': None, 'gridfins': Tr...",...,NaN,NaN,NaN,NaN,NaN,NaN,[],[],NaN,NaN

In [69]:
df["name"].duplicated().sum()

np.int64(0)

In [70]:
df = df[df['upcoming'] == False]

In [71]:
df

,rocket,success,failures,payloads,launchpad,flight_number,name,date_utc,upcoming,cores,...,links.patch.small,links.patch.large,links.reddit.campaign,links.reddit.launch,links.reddit.media,links.reddit.recovery,links.flickr.small,links.flickr.original,links.presskit,links.webcast
0,5e9d0d95eda69955f709d1eb,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",['5eb0e4b5b6c3bb0006eeb1e1'],5e9e4502f5090995de566f86,1,FalconSat,2006-03-24T22:30:00.000Z,False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",...,https://images2.imgbox.com/94/f2/NN6Ph45r_o.png,https://images2.imgbox.com/5b/02/QcxHUb5V_o.png,NaN,NaN,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=0a_00nJ_Y88
1,5e9d0d95eda69955f709d1eb,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",['5eb0e4b6b6c3bb0006eeb1e2'],5e9e4502f5090995de566f86,2,DemoSat,2007-03-21T01:10:00.000Z,False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",...,https://images2.imgbox.com/f9/4a/ZboXReNb_o.png,https://images2.imgbox.com/80/a2/bkWotCIS_o.png,NaN,NaN,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=Lk4zQ2wP-Nc
2,5e9d0d95eda69955f709d1eb,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...","['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",5e9e4502f5090995de566f86,3,Trailblazer,2008-08-03T03:34:00.000Z,False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",...,https://images2.imgbox.com/6c/cb/na1tzhHs_o.png,https://images2.imgbox.com/4a/80/k1oAkY0k_o.png,NaN,NaN,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=v0w9p3U8860
3,5e9d0d95eda69955f709d1eb,True,[],['5eb0e4b7b6c3bb0006eeb1e5'],5e9e4502f5090995de566f86,4,RatSat,2008-09-28T23:15:00.000Z,False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",...,https://images2.imgbox.com/95/39/sRqN7rsv_o.png,https://images2.imgbox.com/a3/99/qswRYzE8_o.png,NaN,NaN,NaN,NaN,[],[],NaN,https://www.youtube.com/watch?v=dLQ2tZEH6G0
4,5e9d0d95eda69955f709d1eb,True,[],['5eb0e4b7b6c3bb0006eeb1e6'],5e9e4502f5090995de566f86,5,RazakSat,2009-07-13T03:35:00.000Z,False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",...,https://images2.imgbox.com/ab/5a/Pequxd5d_o.png,https://images2.imgbox.com/92/e4/7Cf6MLY0_o.png,NaN,NaN,NaN,NaN,[],[],http://www.spacex.com/press/2012/12/19/spacexs...,https://www.youtube.com/watch?v=yTaIDooc8Og
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,5e9d0d95eda69973a809d1ec,True,[],['631614d7ffc78f3b85670716'],5e9e4502f509094188566f88,181,Starlink 4-23 (v1.5),2022-08-28T02:22:00.000Z,False,"[{'core': '61c1ef45a4a2462678cbf45d', 'flight'...",...,https://images2.imgbox.com/12/42/5T8I9wZL_o.png,https://images2.imgbox.com/f4/bc/5iJ5j1Ju_o.png,https://www.reddit.com/r/spacex/comments/jhu37...,NaN,NaN,https://www.reddit.com/r/spacex/comments/k2ts1...,[],[],NaN,https://youtu.be/07RGJ04HRns
187,5e9d0d95eda69973a809d1ec,True,[],"['631614e9ffc78f3b85670717', '631617fbffc78f3b...",5e9e4501f509094ba4566f84,183,Starlink 4-20 (v1.5) & Sherpa LTC-2/Varuna-TDM,2022-09-05T02:09:00.000Z,False,"[{'core': '5e9e28a6f359183c413b265d', 'flight'...",...,https://images2.imgbox.com/dc/a0/erKL6HGq_o.png,https://images2.imgbox.com/57/42/trORYoRc_o.png,https://www.reddit.com/r/spacex/comments/jhu37...,NaN,NaN,https://www.reddit.com/r/spacex/comments/k2ts1...,[],[],NaN,https://youtu.be/NONM-xsKMSs
188,5e9d0d95eda69973a809d1ec,True,[],['630f63bf18702d4844fb5391'],5e9e4502f509092b78566f87,182,Starlink 3-4 (v1.5),2022-08-31T05:40:00.000Z,False,"[{'core': '5f57c54a0622a633027900a1', 'flight'...",...,https://images2.imgbox.com/72/07/PtgYfiFT_o.png,https://images2.imgbox.com/fc/18/97AKS1XR_o.png,https://www.reddit.com/r/spacex/comments/jhu37...,https://www.reddit.com/r/spacex/comments/x1t7g...,NaN,https://www.reddit.com/r/spacex/comments/k2ts1...,[],[],NaN,https://youtu.be/zSJWK_pmXVw
189,5e9d0d95eda69973a809d1ec,True,[],['63161699ffc78f3b85670719'],5e9e4501f509094ba4566f84,185,Starlink 4-34 (v1.5),2022-09-17T01:05:00.000Z,False,"[{'core': '60b800111f83cc1e59f16438', 'flight'...",...,https://images2.imgbox.com/a9/9a/NXVkTZCE_o.png,https://images2.imgbox.com/e3/cc/hN96PmST_o.png,https://www.reddit.com/r/spacex/comments/jhu37...,https://www.reddit.com/r/spacex/comments/xd8vh...,NaN,https://www.reddit.com/r/spacex/comments/k2ts1...,[],[],NaN,https://youtu.be/ZlQHF_yBkMQ
190,5e9d0d95eda69973a809d1ec,True,[],['631616a7ffc78f3b8567071a'],5e9e4501f509094ba4566f84,186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,False,"[{'core': '627843d657b51b752c5c5a53', 'flight'...",...,https://images2.imgbox.com/a9/9a/NXVkTZCE_o.png,https://images2.imgbox.com/e3/cc/hN96PmST_o.png,https://www.reddit.com/r/spacex/comments/jhu37...,https://www.reddit.com/r/spacex/comments/xn028...,NaN,https://www.reddit.com/r/spacex/comments/k2ts1...,[],[],NaN,https://youtu.be/VVu2bSJJhgI

In [72]:
df.columns

Index(['rocket', 'success', 'failures', 'payloads', 'launchpad',
       'flight_number', 'name', 'date_utc', 'upcoming', 'cores', 'id',
       'fairings.reused', 'fairings.recovery_attempt', 'fairings.recovered',
       'fairings.ships', 'links.patch.small', 'links.patch.large',
       'links.reddit.campaign', 'links.reddit.launch', 'links.reddit.media',
       'links.reddit.recovery', 'links.flickr.small', 'links.flickr.original',
       'links.presskit', 'links.webcast'],
      dtype='object')

In [73]:
cols_to_keep = [
    'rocket',
    'launchpad',
    'payloads',
    'flight_number',
    'name',
    'date_utc',
    'success',
    'failures',
    'upcoming',
    'cores'
]

In [74]:
df = df[cols_to_keep]

In [75]:
df

,rocket,launchpad,payloads,flight_number,name,date_utc,success,failures,upcoming,cores
0,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b5b6c3bb0006eeb1e1'],1,FalconSat,2006-03-24T22:30:00.000Z,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",False,"[{'core': '5e9e289df35918033d3b2623', 'flight'..."
1,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b6b6c3bb0006eeb1e2'],2,DemoSat,2007-03-21T01:10:00.000Z,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'..."
2,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,"['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",3,Trailblazer,2008-08-03T03:34:00.000Z,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",False,"[{'core': '5e9e289ef3591814873b2625', 'flight'..."
3,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e5'],4,RatSat,2008-09-28T23:15:00.000Z,True,[],False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'..."
4,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e6'],5,RazakSat,2009-07-13T03:35:00.000Z,True,[],False,"[{'core': '5e9e289ef359184f103b2627', 'flight'..."
...,...,...,...,...,...,...,...,...,...,...
186,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['631614d7ffc78f3b85670716'],181,Starlink 4-23 (v1.5),2022-08-28T02:22:00.000Z,True,[],False,"[{'core': '61c1ef45a4a2462678cbf45d', 'flight'..."
187,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,"['631614e9ffc78f3b85670717', '631617fbffc78f3b...",183,Starlink 4-20 (v1.5) & Sherpa LTC-2/Varuna-TDM,2022-09-05T02:09:00.000Z,True,[],False,"[{'core': '5e9e28a6f359183c413b265d', 'flight'..."
188,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['630f63bf18702d4844fb5391'],182,Starlink 3-4 (v1.5),2022-08-31T05:40:00.000Z,True,[],False,"[{'core': '5f57c54a0622a633027900a1', 'flight'..."
189,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['63161699ffc78f3b85670719'],185,Starlink 4-34 (v1.5),2022-09-17T01:05:00.000Z,True,[],False,"[{'core': '60b800111f83cc1e59f16438', 'flight'..."
190,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['631616a7ffc78f3b8567071a'],186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,True,[],False,"[{'core': '627843d657b51b752c5c5a53', 'flight'..."

ADDING WEATHER TO MY DATASER TO IMPROVE PREDICTIONS

In [76]:
import requests

def get_launchpad_coords(launchpad_id):
    url = f"https://api.spacexdata.com/v4/launchpads/{launchpad_id}"
    res = requests.get(url)
    if res.status_code == 200:
        data = res.json()
        return data["latitude"], data["longitude"]
    else:
        return None, None

In [77]:
# Apply function to each row
df[['latitude', 'longitude']] = df['launchpad'].apply(
    lambda x: pd.Series(get_launchpad_coords(x))
)

C:\Users\Pc World\AppData\Local\Temp\ipykernel_15544\3271126297.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['latitude', 'longitude']] = df['launchpad'].apply(
C:\Users\Pc World\AppData\Local\Temp\ipykernel_15544\3271126297.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['latitude', 'longitude']] = df['launchpad'].apply(

In [78]:
df

,rocket,launchpad,payloads,flight_number,name,date_utc,success,failures,upcoming,cores,latitude,longitude
0,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b5b6c3bb0006eeb1e1'],1,FalconSat,2006-03-24T22:30:00.000Z,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",9.047721,167.743129
1,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b6b6c3bb0006eeb1e2'],2,DemoSat,2007-03-21T01:10:00.000Z,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",9.047721,167.743129
2,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,"['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",3,Trailblazer,2008-08-03T03:34:00.000Z,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",9.047721,167.743129
3,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e5'],4,RatSat,2008-09-28T23:15:00.000Z,True,[],False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",9.047721,167.743129
4,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e6'],5,RazakSat,2009-07-13T03:35:00.000Z,True,[],False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",9.047721,167.743129
...,...,...,...,...,...,...,...,...,...,...,...,...
186,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['631614d7ffc78f3b85670716'],181,Starlink 4-23 (v1.5),2022-08-28T02:22:00.000Z,True,[],False,"[{'core': '61c1ef45a4a2462678cbf45d', 'flight'...",28.608058,-80.603956
187,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,"['631614e9ffc78f3b85670717', '631617fbffc78f3b...",183,Starlink 4-20 (v1.5) & Sherpa LTC-2/Varuna-TDM,2022-09-05T02:09:00.000Z,True,[],False,"[{'core': '5e9e28a6f359183c413b265d', 'flight'...",28.561857,-80.577366
188,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['630f63bf18702d4844fb5391'],182,Starlink 3-4 (v1.5),2022-08-31T05:40:00.000Z,True,[],False,"[{'core': '5f57c54a0622a633027900a1', 'flight'...",34.632093,-120.610829
189,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['63161699ffc78f3b85670719'],185,Starlink 4-34 (v1.5),2022-09-17T01:05:00.000Z,True,[],False,"[{'core': '60b800111f83cc1e59f16438', 'flight'...",28.561857,-80.577366
190,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['631616a7ffc78f3b8567071a'],186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,True,[],False,"[{'core': '627843d657b51b752c5c5a53', 'flight'...",28.561857,-80.577366

In [79]:
df['timestamp'] = pd.to_datetime(df['date_utc']).astype(int) // 10**9

C:\Users\Pc World\AppData\Local\Temp\ipykernel_15544\1879274969.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['timestamp'] = pd.to_datetime(df['date_utc']).astype(int) // 10**9

In [80]:
df

,rocket,launchpad,payloads,flight_number,name,date_utc,success,failures,upcoming,cores,latitude,longitude,timestamp
0,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b5b6c3bb0006eeb1e1'],1,FalconSat,2006-03-24T22:30:00.000Z,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",9.047721,167.743129,1143239400
1,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b6b6c3bb0006eeb1e2'],2,DemoSat,2007-03-21T01:10:00.000Z,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",9.047721,167.743129,1174439400
2,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,"['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",3,Trailblazer,2008-08-03T03:34:00.000Z,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",9.047721,167.743129,1217734440
3,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e5'],4,RatSat,2008-09-28T23:15:00.000Z,True,[],False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",9.047721,167.743129,1222643700
4,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e6'],5,RazakSat,2009-07-13T03:35:00.000Z,True,[],False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",9.047721,167.743129,1247456100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['631614d7ffc78f3b85670716'],181,Starlink 4-23 (v1.5),2022-08-28T02:22:00.000Z,True,[],False,"[{'core': '61c1ef45a4a2462678cbf45d', 'flight'...",28.608058,-80.603956,1661653320
187,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,"['631614e9ffc78f3b85670717', '631617fbffc78f3b...",183,Starlink 4-20 (v1.5) & Sherpa LTC-2/Varuna-TDM,2022-09-05T02:09:00.000Z,True,[],False,"[{'core': '5e9e28a6f359183c413b265d', 'flight'...",28.561857,-80.577366,1662343740
188,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['630f63bf18702d4844fb5391'],182,Starlink 3-4 (v1.5),2022-08-31T05:40:00.000Z,True,[],False,"[{'core': '5f57c54a0622a633027900a1', 'flight'...",34.632093,-120.610829,1661924400
189,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['63161699ffc78f3b85670719'],185,Starlink 4-34 (v1.5),2022-09-17T01:05:00.000Z,True,[],False,"[{'core': '60b800111f83cc1e59f16438', 'flight'...",28.561857,-80.577366,1663376700
190,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['631616a7ffc78f3b8567071a'],186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,True,[],False,"[{'core': '627843d657b51b752c5c5a53', 'flight'...",28.561857,-80.577366,1664062200

In [81]:
import time

def get_weather(lat, lon, timestamp, api_key):
    url = "https://api.openweathermap.org/data/2.5/onecall/timemachine"
    params = {
        "lat": lat,
        "lon": lon,
        "dt": timestamp,
        "appid": api_key,
        "units": "metric"
    }

    try:
        response = requests.get(url, params=params)
        if response.status_code == 200:
            weather = response.json().get("current", {})
            return {
                "temp": weather.get("temp"),
                "wind_speed": weather.get("wind_speed"),
                "humidity": weather.get("humidity"),
                "clouds": weather.get("clouds"),
                "weather_main": weather.get("weather", [{}])[0].get("main")
            }
        else:
            print(f"Failed for timestamp {timestamp}: {response.status_code}")
            return None
    except Exception as e:
        print(f"Error fetching weather: {e}")
        return None

In [82]:

import requests
API_KEY="1c6d6c8c66d90614558e2e2f04e628ef"
lat = 28.5618571   # Example: Cape Canaveral
lon = -80.577366   # Example: Cape Canaveral
ts = 1590866520    # Sample UNIX timestamp (June 2020)

response = requests.get(
    f"http://api.openweathermap.org/data/2.5/onecall/timemachine",
    params={
        "lat": lat,
        "lon": lon,
        "dt": ts,
        "appid": API_KEY,
        "units": "metric"
    }
)

print(response.status_code)
print(response.json())  # Check the contents

401
{'cod': 401, 'message': 'Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.'}

In [83]:
df

,rocket,launchpad,payloads,flight_number,name,date_utc,success,failures,upcoming,cores,latitude,longitude,timestamp
0,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b5b6c3bb0006eeb1e1'],1,FalconSat,2006-03-24T22:30:00.000Z,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",9.047721,167.743129,1143239400
1,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b6b6c3bb0006eeb1e2'],2,DemoSat,2007-03-21T01:10:00.000Z,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",9.047721,167.743129,1174439400
2,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,"['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",3,Trailblazer,2008-08-03T03:34:00.000Z,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",9.047721,167.743129,1217734440
3,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e5'],4,RatSat,2008-09-28T23:15:00.000Z,True,[],False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",9.047721,167.743129,1222643700
4,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e6'],5,RazakSat,2009-07-13T03:35:00.000Z,True,[],False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",9.047721,167.743129,1247456100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['631614d7ffc78f3b85670716'],181,Starlink 4-23 (v1.5),2022-08-28T02:22:00.000Z,True,[],False,"[{'core': '61c1ef45a4a2462678cbf45d', 'flight'...",28.608058,-80.603956,1661653320
187,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,"['631614e9ffc78f3b85670717', '631617fbffc78f3b...",183,Starlink 4-20 (v1.5) & Sherpa LTC-2/Varuna-TDM,2022-09-05T02:09:00.000Z,True,[],False,"[{'core': '5e9e28a6f359183c413b265d', 'flight'...",28.561857,-80.577366,1662343740
188,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['630f63bf18702d4844fb5391'],182,Starlink 3-4 (v1.5),2022-08-31T05:40:00.000Z,True,[],False,"[{'core': '5f57c54a0622a633027900a1', 'flight'...",34.632093,-120.610829,1661924400
189,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['63161699ffc78f3b85670719'],185,Starlink 4-34 (v1.5),2022-09-17T01:05:00.000Z,True,[],False,"[{'core': '60b800111f83cc1e59f16438', 'flight'...",28.561857,-80.577366,1663376700
190,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['631616a7ffc78f3b8567071a'],186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,True,[],False,"[{'core': '627843d657b51b752c5c5a53', 'flight'...",28.561857,-80.577366,1664062200

In [84]:
import requests

def get_weather_openmeteo(lat, lon, date):
    url = "https://archive-api.open-meteo.com/v1/archive"
    
    params = {
        "latitude": lat,
        "longitude": lon,
        "start_date": date,
        "end_date": date,
        "hourly": "temperature_2m,relative_humidity_2m,windspeed_10m,cloudcover",
        "timezone": "UTC"
    }

    response = requests.get(url, params=params)
    if response.status_code == 200:
        data = response.json()
        hourly = data.get("hourly", {})
        # Return average of the day's hourly values (simplified)
        return {
            "temp": sum(hourly.get("temperature_2m", [])) / len(hourly.get("temperature_2m", [])),
            "humidity": sum(hourly.get("relative_humidity_2m", [])) / len(hourly.get("relative_humidity_2m", [])),
            "wind_speed": sum(hourly.get("windspeed_10m", [])) / len(hourly.get("windspeed_10m", [])),
            "cloudcover": sum(hourly.get("cloudcover", [])) / len(hourly.get("cloudcover", []))
        }
    else:
        print("Failed:", response.status_code)
        return None

# Usage
from datetime import datetime

lat = 28.5618571
lon = -80.577366
date = datetime.utcfromtimestamp(1590866520).strftime('%Y-%m-%d')  # Convert timestamp to date

weather = get_weather_openmeteo(lat, lon, date)
print(weather)

C:\Users\Pc World\AppData\Local\Temp\ipykernel_15544\4020766630.py:35: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  date = datetime.utcfromtimestamp(1590866520).strftime('%Y-%m-%d')  # Convert timestamp to date

{'temp': 25.675, 'humidity': 87.08333333333333, 'wind_speed': 7.658333333333334, 'cloudcover': 86.29166666666667}

In [85]:
import requests
from datetime import datetime

def get_weather_open_meteo(lat, lon, utc_date):
    date_str = datetime.strptime(utc_date, "%Y-%m-%dT%H:%M:%S.%fZ").date().isoformat()
    
    url = "https://archive-api.open-meteo.com/v1/archive"
    params = {
        "latitude": lat,
        "longitude": lon,
        "start_date": date_str,
        "end_date": date_str,
        "hourly": "temperature_2m,wind_speed_10m,relative_humidity_2m,cloudcover",
        "timezone": "UTC"
    }

    response = requests.get(url, params=params)
    if response.status_code == 200:
        hourly = response.json().get("hourly", {})
        return {
            "temp": hourly.get("temperature_2m", [None])[0],
            "wind_speed": hourly.get("wind_speed_10m", [None])[0],
            "humidity": hourly.get("relative_humidity_2m", [None])[0],
            "clouds": hourly.get("cloudcover", [None])[0]
        }
    else:
        return {"temp": None, "wind_speed": None, "humidity": None, "clouds": None}

In [86]:
weather_data = []

for _, row in df.iterrows():
    lat = row["latitude"]
    lon = row["longitude"]
    utc_date = row["date_utc"]

    weather = get_weather_open_meteo(lat, lon, utc_date)
    weather_data.append(weather)

weather_df = pd.DataFrame(weather_data)
df = pd.concat([df.reset_index(drop=True), weather_df], axis=1)
df.to_csv("spacex_weather_enriched.csv", index=False)

In [87]:
df

,rocket,launchpad,payloads,flight_number,name,date_utc,success,failures,upcoming,cores,latitude,longitude,timestamp,temp,wind_speed,humidity,clouds
0,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b5b6c3bb0006eeb1e1'],1,FalconSat,2006-03-24T22:30:00.000Z,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",9.047721,167.743129,1143239400,27.1,32.5,73,52
1,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b6b6c3bb0006eeb1e2'],2,DemoSat,2007-03-21T01:10:00.000Z,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",9.047721,167.743129,1174439400,27.3,33.3,80,57
2,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,"['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",3,Trailblazer,2008-08-03T03:34:00.000Z,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",9.047721,167.743129,1217734440,27.6,18.6,78,28
3,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e5'],4,RatSat,2008-09-28T23:15:00.000Z,True,[],False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",9.047721,167.743129,1222643700,26.7,17.6,82,52
4,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e6'],5,RazakSat,2009-07-13T03:35:00.000Z,True,[],False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",9.047721,167.743129,1247456100,27.7,27.6,84,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['631614d7ffc78f3b85670716'],181,Starlink 4-23 (v1.5),2022-08-28T02:22:00.000Z,True,[],False,"[{'core': '61c1ef45a4a2462678cbf45d', 'flight'...",28.608058,-80.603956,1661653320,25.8,9.7,94,100
183,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,"['631614e9ffc78f3b85670717', '631617fbffc78f3b...",183,Starlink 4-20 (v1.5) & Sherpa LTC-2/Varuna-TDM,2022-09-05T02:09:00.000Z,True,[],False,"[{'core': '5e9e28a6f359183c413b265d', 'flight'...",28.561857,-80.577366,1662343740,28.7,10.9,73,100
184,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['630f63bf18702d4844fb5391'],182,Starlink 3-4 (v1.5),2022-08-31T05:40:00.000Z,True,[],False,"[{'core': '5f57c54a0622a633027900a1', 'flight'...",34.632093,-120.610829,1661924400,15.2,16.6,83,76
185,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['63161699ffc78f3b85670719'],185,Starlink 4-34 (v1.5),2022-09-17T01:05:00.000Z,True,[],False,"[{'core': '60b800111f83cc1e59f16438', 'flight'...",28.561857,-80.577366,1663376700,23.6,10.4,95,100
186,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['631616a7ffc78f3b8567071a'],186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,True,[],False,"[{'core': '627843d657b51b752c5c5a53', 'flight'...",28.561857,-80.577366,1664062200,26.4,16.6,79,17

In [88]:
df.dropna()

,rocket,launchpad,payloads,flight_number,name,date_utc,success,failures,upcoming,cores,latitude,longitude,timestamp,temp,wind_speed,humidity,clouds
0,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b5b6c3bb0006eeb1e1'],1,FalconSat,2006-03-24T22:30:00.000Z,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",9.047721,167.743129,1143239400,27.1,32.5,73,52
1,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b6b6c3bb0006eeb1e2'],2,DemoSat,2007-03-21T01:10:00.000Z,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",9.047721,167.743129,1174439400,27.3,33.3,80,57
2,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,"['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",3,Trailblazer,2008-08-03T03:34:00.000Z,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",9.047721,167.743129,1217734440,27.6,18.6,78,28
3,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e5'],4,RatSat,2008-09-28T23:15:00.000Z,True,[],False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",9.047721,167.743129,1222643700,26.7,17.6,82,52
4,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e6'],5,RazakSat,2009-07-13T03:35:00.000Z,True,[],False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",9.047721,167.743129,1247456100,27.7,27.6,84,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['631614d7ffc78f3b85670716'],181,Starlink 4-23 (v1.5),2022-08-28T02:22:00.000Z,True,[],False,"[{'core': '61c1ef45a4a2462678cbf45d', 'flight'...",28.608058,-80.603956,1661653320,25.8,9.7,94,100
183,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,"['631614e9ffc78f3b85670717', '631617fbffc78f3b...",183,Starlink 4-20 (v1.5) & Sherpa LTC-2/Varuna-TDM,2022-09-05T02:09:00.000Z,True,[],False,"[{'core': '5e9e28a6f359183c413b265d', 'flight'...",28.561857,-80.577366,1662343740,28.7,10.9,73,100
184,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['630f63bf18702d4844fb5391'],182,Starlink 3-4 (v1.5),2022-08-31T05:40:00.000Z,True,[],False,"[{'core': '5f57c54a0622a633027900a1', 'flight'...",34.632093,-120.610829,1661924400,15.2,16.6,83,76
185,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['63161699ffc78f3b85670719'],185,Starlink 4-34 (v1.5),2022-09-17T01:05:00.000Z,True,[],False,"[{'core': '60b800111f83cc1e59f16438', 'flight'...",28.561857,-80.577366,1663376700,23.6,10.4,95,100
186,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['631616a7ffc78f3b8567071a'],186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,True,[],False,"[{'core': '627843d657b51b752c5c5a53', 'flight'...",28.561857,-80.577366,1664062200,26.4,16.6,79,17

In [89]:
df.tail()

,rocket,launchpad,payloads,flight_number,name,date_utc,success,failures,upcoming,cores,latitude,longitude,timestamp,temp,wind_speed,humidity,clouds
182,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['631614d7ffc78f3b85670716'],181,Starlink 4-23 (v1.5),2022-08-28T02:22:00.000Z,True,[],False,"[{'core': '61c1ef45a4a2462678cbf45d', 'flight'...",28.608058,-80.603956,1661653320,25.8,9.7,94,100
183,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,"['631614e9ffc78f3b85670717', '631617fbffc78f3b...",183,Starlink 4-20 (v1.5) & Sherpa LTC-2/Varuna-TDM,2022-09-05T02:09:00.000Z,True,[],False,"[{'core': '5e9e28a6f359183c413b265d', 'flight'...",28.561857,-80.577366,1662343740,28.7,10.9,73,100
184,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['630f63bf18702d4844fb5391'],182,Starlink 3-4 (v1.5),2022-08-31T05:40:00.000Z,True,[],False,"[{'core': '5f57c54a0622a633027900a1', 'flight'...",34.632093,-120.610829,1661924400,15.2,16.6,83,76
185,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['63161699ffc78f3b85670719'],185,Starlink 4-34 (v1.5),2022-09-17T01:05:00.000Z,True,[],False,"[{'core': '60b800111f83cc1e59f16438', 'flight'...",28.561857,-80.577366,1663376700,23.6,10.4,95,100
186,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['631616a7ffc78f3b8567071a'],186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,True,[],False,"[{'core': '627843d657b51b752c5c5a53', 'flight'...",28.561857,-80.577366,1664062200,26.4,16.6,79,17

In [90]:
df.columns

Index(['rocket', 'launchpad', 'payloads', 'flight_number', 'name', 'date_utc',
       'success', 'failures', 'upcoming', 'cores', 'latitude', 'longitude',
       'timestamp', 'temp', 'wind_speed', 'humidity', 'clouds'],
      dtype='object')

In [91]:
df.failures

0      [{'time': 33, 'altitude': None, 'reason': 'mer...
1      [{'time': 301, 'altitude': 289, 'reason': 'har...
2      [{'time': 140, 'altitude': 35, 'reason': 'resi...
3                                                     []
4                                                     []
                             ...
182                                                   []
183                                                   []
184                                                   []
185                                                   []
186                                                   []
Name: failures, Length: 187, dtype: object

In [92]:
df.sample(50)

,rocket,launchpad,payloads,flight_number,name,date_utc,success,failures,upcoming,cores,latitude,longitude,timestamp,temp,wind_speed,humidity,clouds
130,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['60428afbc041c16716f73cdd'],121,Starlink-22 (v1.0),2021-03-24T08:28:00.000Z,True,[],False,"[{'core': '5ef670f10059c33cee4a826c', 'flight'...",28.561857,-80.577366,1616574480,20.1,9.0,72,82
186,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['631616a7ffc78f3b8567071a'],186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,True,[],False,"[{'core': '627843d657b51b752c5c5a53', 'flight'...",28.561857,-80.577366,1664062200,26.4,16.6,79,17
134,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,"['605b4bfcaa5433645e37d048', '609f48374a12e469...",127,Starlink-26 (v1.0) + Capella-6 + Tyvak-0130,2021-05-15T22:54:00.000Z,True,[],False,"[{'core': '5e9e28a7f3591817f23b2663', 'flight'...",28.608058,-80.603956,1621119240,23.3,19.3,69,20
176,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['630bcfe1d36448026ab01641'],177,KPLO,2022-08-04T23:08:00.000Z,True,[],False,"[{'core': '5e9e28a6f359183c413b265d', 'flight'...",28.561857,-80.577366,1659654480,29.0,4.0,67,17
25,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['5eb0e4beb6c3bb0006eeb1fe'],26,Jason 3,2016-01-17T15:42:00.000Z,True,[],False,"[{'core': '5e9e28a1f3591842fa3b263c', 'flight'...",34.632093,-120.610829,1453045320,14.0,20.2,87,100
66,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4c9b6c3bb0006eeb22a'],67,Merah Putih,2018-08-07T05:18:00.000Z,True,[],False,"[{'core': '5e9e28a5f359182b023b2656', 'flight'...",28.561857,-80.577366,1533619080,27.7,10.2,79,8
32,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4c1b6c3bb0006eeb206'],33,JCSAT-16,2016-08-14T05:26:00.000Z,True,[],False,"[{'core': '5e9e28a2f35918b8243b2643', 'flight'...",28.561857,-80.577366,1471152360,28.0,13.5,84,15
7,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4bab6c3bb0006eeb1ea'],8,COTS 2,2012-05-22T07:44:00.000Z,True,[],False,"[{'core': '5e9e289ef35918f39c3b262a', 'flight'...",28.561857,-80.577366,1337672640,24.5,15.1,74,1
161,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['6243b39daf52800c6e919267'],165,Transporter-5,2022-05-25T18:27:00.000Z,True,[],False,"[{'core': '5f57c53d0622a6330279009f', 'flight'...",28.561857,-80.577366,1653503220,26.2,15.3,69,25
35,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['5eb0e4c3b6c3bb0006eeb209'],36,CRS-10,2017-02-19T14:39:00.000Z,True,[],False,"[{'core': '5e9e28a3f3591829dc3b2646', 'flight'...",28.608058,-80.603956,1487515140,22.2,4.8,70,87
133,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['605b4befaa5433645e37d047'],125,Starlink-25 (v1.0),2021-05-04T19:01:00.000Z,True,[],False,"[{'core': '5e9e28a5f3591833b13b2659', 'flight'...",28.608058,-80.603956,1620154860,27.0,14.7,71,66
49,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['5eb0e4c5b6c3bb0006eeb217'],50,KoreaSat 5A,2017-10-30T19:34:00.000Z,True,[],False,"[{'core': '5e9e28a4f359185cc03b2651', 'flight'...",28.608058,-80.603956,1509392040,15.8,18.2,45,0
46,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['5eb0e4c5b6c3bb0006eeb214'],47,Boeing X-37B OTV-5,2017-09-07T13:50:00.000Z,True,[],False,"[{'core': '5e9e28a4f3591845123b264f', 'flight'...",28.608058,-80.603956,1504792200,26.5,6.2,88,98
83,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4cfb6c3bb0006eeb24c'],84,Starlink-1,2019-11-11T14:56:00.000Z,True,[],False,"[{'core': '5e9e28a5f3591809c03b2658', 'flight'...",28.561857,-80.577366,1573484160,20.4,11.9,72,36
147,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['61d5ece4f88e4c5fc91f1ebb'],144,Starlink 4-5 (v1.5),2022-01-06T21:49:00.000Z,True,[],False,"[{'core': '5f57c5440622a633027900a0', 'flight'...",28.608058,-80.603956,1641505740,20.5,5.8,74,71
89,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4d0b6c3bb0006eeb252'],90,Starlink-4,2020-02-17T15:05:55.000Z,True,[],False,"[{'core': '5e9e28a7f3591809313b2660', 'flight'...",28.561857,-80.577366,1581951955,20.9,10.5,91,77
26,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4beb6c3bb0006eeb1ff'],27,SES-9,2016-03-04T23:35:00.000Z,True,[],False,"[{'core': '5e9e28a1f359188def3b263d', 'flight'...",28.561857,-80.577366,1457134500,22.1,10.7,56,97
72,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4cab6c3bb0006eeb230'],73,GPS III SV01,2018-12-23T13:51:00.000Z,True,[],False,"[{'core': '5e9e28a6f35918513b3b265b', 'flight'...",28.561857,-80.577366,1545573060,11.5,6.9,74,0
22,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4beb6c3bb0006eeb1fb'],23,TürkmenÄlem 52°E / MonacoSAT,2015-04-27T23:03:00.000Z,True,[],False,"[{'core': '5e9e28a1f35918233f3b2639', 'flight'...",28.561857,-80.577366,1430175780,27.8,15.5,69,67
14,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4bcb6c3bb0006eeb1f2'],15,OG-2 Mission 1,2014-07-14T15:15:00.000Z,True,[],False,"[{'core': '5e9e28a0f3591870a63b2631', 'flight'...",28.561857,-80.577366,1405350900,26.5,15.3,85,51
36,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['5eb0e4c3b6c3bb0006eeb20a'],37,EchoStar 23,2017-03-16T06:00:00.000Z,True,[],False,"[{'core': '5e9e28a3f3591878473b2647', 'flight'...",28.608058,-80.603956,1489644000,11.2,10.6,57,0
27,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4bfb6c3bb0006eeb200'],28,CRS-8,2016-04-08T20:43:00.000Z,True,[],False,"[{'core': '5e9e28a2f359182d0b3b263e', 'flight'...",28.561857,-80.577366,1460148180,25.2,19.2,49,1
110,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['5ef6a4d50059c33cee4a82a1'],104,Starlink-13 (v1.0),2020-10-18T12:25:00.000Z,True,[],False,"[{'core': '5e9e28a6f35918c0803b265c', 'flight'...",28.608058,-80.603956,1603023900,25.0,11.6,84,45
135,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['6079bd5e9a06446e8c61bf7c'],126,Starlink-27 (v1.0),2021-05-09T06:42:00.000Z,True,[],False,"[{'core': '5e9e28a6f35918c0803b265c', 'flight'...",28.561857,-80.577366,1620542520,22.0,9.4,59,0
165,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['625829d75988f159024b9649'],162,Starlink 4-13 (v1.5),2022-05-13T22:07:00.000Z,True,[],False,"[{'core': '5f57c54a0622a633027900a1', 'flight'...",34.632093,-120.610829,1652479620,12.1,23.5,70,0
88,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4d0b6c3bb0006eeb251'],89,Starlink-3,2020-01-29T14:06:00.000Z,True,[],False,"[{'core': '5e9e28a6f35918c0803b265c', 'flight'...",28.561857,-80.577366,1580306760,14.3,11.3,72,0
105,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,"['5ed9858b1f30554030d45c3e', '5ee522e32f1f3d47...",99,Starlink-9 (v1.0) & BlackSky Global 5-6,2020-08-07T05:12:00.000Z,True,[],False,"[{'core': '5e9e28a6f35918c0803b265c', 'flight'...",28.608058,-80.603956,1596777120,27.3,1.6,88,99
78,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4cbb6c3bb0006eeb238'],79,Starlink v0.9,2019-05-24T02:30:00.000Z,True,[],False,"[{'core': '5e9e28a5f3591833b13b2659', 'flight'...",28.561857,-80.577366,1558665000,25.6,19.4,65,23
60,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['5eb0e4c7b6c3bb0006eeb223'],61,Bangabandhu-1,2018-05-11T20:14:00.000Z,True,[],False,"[{'core': '5e9e28a5f359182b023b2656', 'flight'...",28.608058,-80.603956,1526069640,23.3,6.1,68,86
92,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['5eb0e4d1b6c3bb0006eeb255'],93,Starlink-6,2020-04-22T19:30:00.000Z,True,[],False,"[{'core': '5e9e28a6f35918c0803b265c', 'flight'...",28.608058,-80.603956,1587583800,23.3,5.4,64,90
45,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['5eb0e4c4b6c3bb0006eeb213'],46,FormoSat-5,2017-08-24T18:50:00.000Z,True,[],False,"[{'core': '5e9e28a4f359182d843b264e', 'flight'...",34.632093,-120.610829,1503600600,16.4,16.9,86,100
85,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4cfb6c3bb0006eeb24e'],86,JCSat 18 / Kacific 1,2019-12-17T00:10:00.000Z,True,[],False,"[{'core': '5e9e28a7f3591809313b2660', 'flight'...",28.561857,-80.577366,1576541400,22.6,16.3,88,18
181,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['630bceadd36448026ab0163f'],180,Starlink 4-27 (v1.5),2022-08-19T19:24:00.000Z,True,[],False,"[{'core': '5f57c5440622a633027900a0', 'flight'...",28.561857,-80.577366,1660937040,25.3,4.2,88,100
106,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5ed9859f1f30554030d45c3f'],100,Starlink-10 (v1.0) & SkySat 19-21,2020-08-18T14:31:00.000Z,True,[],False,"[{'core': '5e9e28a5f3591833b13b2659', 'flight'...",28.561857,-80.577366,1597761060,27.6,9.4,81,77
153,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['61fc0379e0dc5662b76489b6'],152,Starlink 4-9 (v1.5),2022-03-03T14:35:00.000Z,True,[],False,"[{'core': '5ef670f10059c33cee4a826c', 'flight'...",28.608058,-80.603956,1646318100,19.4,9.2,81,0
148,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['61e05516be8d8b66799018d4'],146,Starlink 4-6 (v1.5),2022-01-19T00:04:00.000Z,True,[],False,"[{'core': '5ef670f10059c33cee4a826c', 'flight'...",28.608058,-80.603956,1642550640,10.5,8.8,86,4
3,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e5'],4,RatSat,2008-09-28T23:15:00.000Z,True,[],False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",9.047721,167.743129,1222643700,26.7,17.6,82,52
137,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['6175aaacefa4314085aa9c56'],148,NROL-87,2022-02-02T20:18:00.000Z,True,[],False,"[{'core': '61fae5947aa67176fe3e0e1e', 'flight'...",34.632093,-120.610829,1643833080,12.6,26.6,56,0
57,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['5eb0e4c7b6c3bb0006eeb220'],58,Iridium NEXT Mission 5,2018-03-30T14:13:51.000Z,True,[],False,"[{'core': '5e9e28a4f3591843103b2650', 'flight'...",34.632093,-120.610829,1522419231,16.6,7.4,70,0
70,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['5eb0e4c9b6c3bb0006eeb22e'],71,SSO-A,2018-12-03T18:34:00.000Z,True,[],False,"[{'core': '5e9e28a5f359182b023b2656', 'flight'...",34.632093,-120.610829,1543862040,12.5,16.1,57,15
168,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['62615ee40ec008379be596fd'],164,Starlink 4-18 (v1.5),2022-05-18T10:40:00.000Z,True,[],False,"[{'core': '5e9e28a6f359183c413b265d', 'flight'...",28.608058,-80.603956,1652870400,26.8,15.8,65,29
28,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4bfb6c3bb0006eeb201'],29,JCSAT-2B,2016-05-06T05:21:00.000Z,True,[],False,"[{'core': '5e9e28a2f35918077b3b263f', 'flight'...",28.561857,-80.577366,1462512060,23.4,23.0,41,0
58,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5eb0e4c7b6c3bb0006eeb221'],59,CRS-14,2018-04-02T20:30:41.000Z,True,[],False,"[{'core': '5e9e28a4f3591884ee3b264d', 'flight'...",28.561857,-80.577366,1522701041,21.2,9.7,88,22
119,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['5fe3b57db3467846b324217a'],130,SXM-8,2021-06-06T04:26:00.000Z,True,[],False,"[{'core': '5f57c53d0622a6330279009f', 'flight'...",28.561857,-80.577366,1622953560,27.1,16.5,79,99
124,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['5fe3b3bab3467846b3242174'],136,Crew-3,2021-11-11T02:03:00.000Z,True,[],False,"[{'core': '60b800111f83cc1e59f16438', 'flight'...",28.608058,-80.603956,1636596180,21.0,7.7,89,100
145,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['61bbac16437241381bf70632'],141,Starlink 4-4 (v1.5),2021-12-18T12:41:40.000Z,True,[],False,"[{'core': '5e9e28a6f35918c0803b265c', 'flight'...",34.632093,-120.610829,1639831300,12.4,12.7,81,0
94,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['5eb0e4d1b6c3bb0006eeb257'],94,CCtCap Demo Mission 2,2020-05-30T19:22:00.000Z,True,[],False,"[{'core': '5e9e28a7f3591817f23b2663', 'flight'...",28.608058,-80.603956,1590866520,27.0,11.3,81,100
10,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['5eb0e4bbb6c3bb0006eeb1ee'],11,CASSIOPE,2013-09-29T16:00:00.000Z,True,[],False,"[{'core': '5e9e289ff359180ae23b262d', 'flight'...",34.632093,-120.610829,1380470400,17.6,12.6,55,1
171,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['630bccc6d36448026ab01639'],171,Starlink 4-21 (v1.5),2022-07-07T13:11:00.000Z,True,[],False,"[{'core': '5e9e28a7f3591817f23b2663', 'flight'...",28.561857,-80.577366,1657199460,29.0,15.4,76,87
136,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['6079bd679a06446e8c61bf7d'],128,Starlink-28 (v1.0),2021-05-26T18:59:00.000Z,True,[],False,"[{'core': '5f57c54a0622a633027900a1', 'flight'...",28.561857,-80.577366,1622055540,24.9,13.6,72,32

In [93]:
df.drop(columns=["failures"], inplace=True)

In [94]:
df

,rocket,launchpad,payloads,flight_number,name,date_utc,success,upcoming,cores,latitude,longitude,timestamp,temp,wind_speed,humidity,clouds
0,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b5b6c3bb0006eeb1e1'],1,FalconSat,2006-03-24T22:30:00.000Z,False,False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",9.047721,167.743129,1143239400,27.1,32.5,73,52
1,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b6b6c3bb0006eeb1e2'],2,DemoSat,2007-03-21T01:10:00.000Z,False,False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",9.047721,167.743129,1174439400,27.3,33.3,80,57
2,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,"['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",3,Trailblazer,2008-08-03T03:34:00.000Z,False,False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",9.047721,167.743129,1217734440,27.6,18.6,78,28
3,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e5'],4,RatSat,2008-09-28T23:15:00.000Z,True,False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",9.047721,167.743129,1222643700,26.7,17.6,82,52
4,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e6'],5,RazakSat,2009-07-13T03:35:00.000Z,True,False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",9.047721,167.743129,1247456100,27.7,27.6,84,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['631614d7ffc78f3b85670716'],181,Starlink 4-23 (v1.5),2022-08-28T02:22:00.000Z,True,False,"[{'core': '61c1ef45a4a2462678cbf45d', 'flight'...",28.608058,-80.603956,1661653320,25.8,9.7,94,100
183,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,"['631614e9ffc78f3b85670717', '631617fbffc78f3b...",183,Starlink 4-20 (v1.5) & Sherpa LTC-2/Varuna-TDM,2022-09-05T02:09:00.000Z,True,False,"[{'core': '5e9e28a6f359183c413b265d', 'flight'...",28.561857,-80.577366,1662343740,28.7,10.9,73,100
184,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['630f63bf18702d4844fb5391'],182,Starlink 3-4 (v1.5),2022-08-31T05:40:00.000Z,True,False,"[{'core': '5f57c54a0622a633027900a1', 'flight'...",34.632093,-120.610829,1661924400,15.2,16.6,83,76
185,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['63161699ffc78f3b85670719'],185,Starlink 4-34 (v1.5),2022-09-17T01:05:00.000Z,True,False,"[{'core': '60b800111f83cc1e59f16438', 'flight'...",28.561857,-80.577366,1663376700,23.6,10.4,95,100
186,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['631616a7ffc78f3b8567071a'],186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,True,False,"[{'core': '627843d657b51b752c5c5a53', 'flight'...",28.561857,-80.577366,1664062200,26.4,16.6,79,17

In [116]:
import numpy as np
df[df['success']==np.nan]

Empty DataFrame
Columns: [rocket, launchpad, payloads, flight_number, name, date_utc, success, upcoming, cores, latitude, longitude, timestamp, temp, wind_speed, humidity, clouds]
Index: []

In [109]:
df['success']=df['success'].dropna()

In [117]:
df = df[df['success'].notna()]

In [118]:
df.isnull().sum()

rocket           0
launchpad        0
payloads         0
flight_number    0
name             0
date_utc         0
success          0
upcoming         0
cores            0
latitude         0
longitude        0
timestamp        0
temp             0
wind_speed       0
humidity         0
clouds           0
dtype: int64

In [111]:
import numpy as np
df['success'].replace(np.nan,'True')

0      False
1      False
2      False
3       True
4       True
       ...
182     True
183     True
184     True
185     True
186     True
Name: success, Length: 187, dtype: object

In [ ]:
df.columns.value_counts()

rocket           1
launchpad        1
payloads         1
flight_number    1
name             1
date_utc         1
upcoming         1
cores            1
latitude         1
longitude        1
temp             1
wind_speed       1
humidity         1
clouds           1
Name: count, dtype: int64

In [120]:
df

,rocket,launchpad,payloads,flight_number,name,date_utc,success,upcoming,cores,latitude,longitude,timestamp,temp,wind_speed,humidity,clouds
0,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b5b6c3bb0006eeb1e1'],1,FalconSat,2006-03-24T22:30:00.000Z,False,False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",9.047721,167.743129,1143239400,27.1,32.5,73,52
1,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b6b6c3bb0006eeb1e2'],2,DemoSat,2007-03-21T01:10:00.000Z,False,False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",9.047721,167.743129,1174439400,27.3,33.3,80,57
2,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,"['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",3,Trailblazer,2008-08-03T03:34:00.000Z,False,False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",9.047721,167.743129,1217734440,27.6,18.6,78,28
3,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e5'],4,RatSat,2008-09-28T23:15:00.000Z,True,False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",9.047721,167.743129,1222643700,26.7,17.6,82,52
4,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e6'],5,RazakSat,2009-07-13T03:35:00.000Z,True,False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",9.047721,167.743129,1247456100,27.7,27.6,84,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['631614d7ffc78f3b85670716'],181,Starlink 4-23 (v1.5),2022-08-28T02:22:00.000Z,True,False,"[{'core': '61c1ef45a4a2462678cbf45d', 'flight'...",28.608058,-80.603956,1661653320,25.8,9.7,94,100
183,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,"['631614e9ffc78f3b85670717', '631617fbffc78f3b...",183,Starlink 4-20 (v1.5) & Sherpa LTC-2/Varuna-TDM,2022-09-05T02:09:00.000Z,True,False,"[{'core': '5e9e28a6f359183c413b265d', 'flight'...",28.561857,-80.577366,1662343740,28.7,10.9,73,100
184,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['630f63bf18702d4844fb5391'],182,Starlink 3-4 (v1.5),2022-08-31T05:40:00.000Z,True,False,"[{'core': '5f57c54a0622a633027900a1', 'flight'...",34.632093,-120.610829,1661924400,15.2,16.6,83,76
185,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['63161699ffc78f3b85670719'],185,Starlink 4-34 (v1.5),2022-09-17T01:05:00.000Z,True,False,"[{'core': '60b800111f83cc1e59f16438', 'flight'...",28.561857,-80.577366,1663376700,23.6,10.4,95,100
186,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['631616a7ffc78f3b8567071a'],186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,True,False,"[{'core': '627843d657b51b752c5c5a53', 'flight'...",28.561857,-80.577366,1664062200,26.4,16.6,79,17

In [122]:
# First: inspect the column
df['cores'].iloc[40]

"[{'core': '5e9e28a3f3591856803b264a', 'flight': 1, 'gridfins': True, 'legs': True, 'reused': False, 'landing_attempt': True, 'landing_success': True, 'landing_type': 'RTLS', 'landpad': '5e9e3032383ecb267a34e7c7'}]"

In [123]:
df['core_reused'] = df['cores'].apply(lambda x: x[0]['reused'] if x and isinstance(x, list) else None)
df['landing_attempt'] = df['cores'].apply(lambda x: x[0]['landing_attempt'] if x and isinstance(x, list) else None)
df['landing_success'] = df['cores'].apply(lambda x: x[0]['landing_success'] if x and isinstance(x, list) else None)
df['landing_type'] = df['cores'].apply(lambda x: x[0]['landing_type'] if x and isinstance(x, list) else None)

C:\Users\Pc World\AppData\Local\Temp\ipykernel_15544\3472949828.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['core_reused'] = df['cores'].apply(lambda x: x[0]['reused'] if x and isinstance(x, list) else None)
C:\Users\Pc World\AppData\Local\Temp\ipykernel_15544\3472949828.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['landing_attempt'] = df['cores'].apply(lambda x: x[0]['landing_attempt'] if x and isinstance(x, list) else None)
C:\Users\Pc World\AppData\Local\Temp\ipykernel_15544\3472949828.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['landing_success'] = df['cores'].apply(lambda x: x[0]['landing_success'] if x and isinstance(x, list) else None)
C:\Users\Pc World\AppData\Local\Temp\ipykernel_15544\3472949828.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['landing_type'] = df['cores'].apply(lambda x: x[0]['landing_type'] if x and isinstance(x, list) else None)

In [124]:
df.drop(columns=['cores'], inplace=True)

C:\Users\Pc World\AppData\Local\Temp\ipykernel_15544\2505031949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['cores'], inplace=True)

In [130]:
df

,rocket,launchpad,payloads,flight_number,name,date_utc,success,upcoming,latitude,longitude,timestamp,temp,wind_speed,humidity,clouds,core_reused,landing_attempt,landing_success,landing_type
0,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b5b6c3bb0006eeb1e1'],1,FalconSat,2006-03-24T22:30:00.000Z,False,False,9.047721,167.743129,1143239400,27.1,32.5,73,52,NaN,NaN,NaN,NaN
1,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b6b6c3bb0006eeb1e2'],2,DemoSat,2007-03-21T01:10:00.000Z,False,False,9.047721,167.743129,1174439400,27.3,33.3,80,57,NaN,NaN,NaN,NaN
2,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,"['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",3,Trailblazer,2008-08-03T03:34:00.000Z,False,False,9.047721,167.743129,1217734440,27.6,18.6,78,28,NaN,NaN,NaN,NaN
3,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e5'],4,RatSat,2008-09-28T23:15:00.000Z,True,False,9.047721,167.743129,1222643700,26.7,17.6,82,52,NaN,NaN,NaN,NaN
4,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e6'],5,RazakSat,2009-07-13T03:35:00.000Z,True,False,9.047721,167.743129,1247456100,27.7,27.6,84,68,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['631614d7ffc78f3b85670716'],181,Starlink 4-23 (v1.5),2022-08-28T02:22:00.000Z,True,False,28.608058,-80.603956,1661653320,25.8,9.7,94,100,NaN,NaN,NaN,NaN
182,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,"['631614e9ffc78f3b85670717', '631617fbffc78f3b...",183,Starlink 4-20 (v1.5) & Sherpa LTC-2/Varuna-TDM,2022-09-05T02:09:00.000Z,True,False,28.561857,-80.577366,1662343740,28.7,10.9,73,100,NaN,NaN,NaN,NaN
183,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['630f63bf18702d4844fb5391'],182,Starlink 3-4 (v1.5),2022-08-31T05:40:00.000Z,True,False,34.632093,-120.610829,1661924400,15.2,16.6,83,76,NaN,NaN,NaN,NaN
184,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['63161699ffc78f3b85670719'],185,Starlink 4-34 (v1.5),2022-09-17T01:05:00.000Z,True,False,28.561857,-80.577366,1663376700,23.6,10.4,95,100,NaN,NaN,NaN,NaN
185,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['631616a7ffc78f3b8567071a'],186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,True,False,28.561857,-80.577366,1664062200,26.4,16.6,79,17,NaN,NaN,NaN,NaN

In [126]:
df['landing_type'].unique()

array([None], dtype=object)

In [127]:
df.to_csv("spacex_cleaned.csv", index=False)
print("✅ Cleaned data saved to spacex_cleaned.csv")

✅ Cleaned data saved to spacex_cleaned.csv

In [128]:
import pandas as pd

# Load your cleaned CSV
df = pd.read_csv("spacex_cleaned.csv")

# Auto-detect object-type (categorical) columns
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

# Remove columns you don't want to encode (like 'date_utc', or high-cardinality IDs)
categorical_cols = [col for col in categorical_cols if col not in ['date_utc', 'name', 'payloads', 'cores']]

# One-hot encode
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Save the final preprocessed version
df_encoded.to_csv("spacex_ready_for_model.csv", index=False)

print("✅ One-hot encoding complete. Data saved to spacex_ready_for_model.csv")

✅ One-hot encoding complete. Data saved to spacex_ready_for_model.csv

In [129]:
df

,rocket,launchpad,payloads,flight_number,name,date_utc,success,upcoming,latitude,longitude,timestamp,temp,wind_speed,humidity,clouds,core_reused,landing_attempt,landing_success,landing_type
0,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b5b6c3bb0006eeb1e1'],1,FalconSat,2006-03-24T22:30:00.000Z,False,False,9.047721,167.743129,1143239400,27.1,32.5,73,52,NaN,NaN,NaN,NaN
1,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b6b6c3bb0006eeb1e2'],2,DemoSat,2007-03-21T01:10:00.000Z,False,False,9.047721,167.743129,1174439400,27.3,33.3,80,57,NaN,NaN,NaN,NaN
2,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,"['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",3,Trailblazer,2008-08-03T03:34:00.000Z,False,False,9.047721,167.743129,1217734440,27.6,18.6,78,28,NaN,NaN,NaN,NaN
3,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e5'],4,RatSat,2008-09-28T23:15:00.000Z,True,False,9.047721,167.743129,1222643700,26.7,17.6,82,52,NaN,NaN,NaN,NaN
4,5e9d0d95eda69955f709d1eb,5e9e4502f5090995de566f86,['5eb0e4b7b6c3bb0006eeb1e6'],5,RazakSat,2009-07-13T03:35:00.000Z,True,False,9.047721,167.743129,1247456100,27.7,27.6,84,68,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,5e9d0d95eda69973a809d1ec,5e9e4502f509094188566f88,['631614d7ffc78f3b85670716'],181,Starlink 4-23 (v1.5),2022-08-28T02:22:00.000Z,True,False,28.608058,-80.603956,1661653320,25.8,9.7,94,100,NaN,NaN,NaN,NaN
182,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,"['631614e9ffc78f3b85670717', '631617fbffc78f3b...",183,Starlink 4-20 (v1.5) & Sherpa LTC-2/Varuna-TDM,2022-09-05T02:09:00.000Z,True,False,28.561857,-80.577366,1662343740,28.7,10.9,73,100,NaN,NaN,NaN,NaN
183,5e9d0d95eda69973a809d1ec,5e9e4502f509092b78566f87,['630f63bf18702d4844fb5391'],182,Starlink 3-4 (v1.5),2022-08-31T05:40:00.000Z,True,False,34.632093,-120.610829,1661924400,15.2,16.6,83,76,NaN,NaN,NaN,NaN
184,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['63161699ffc78f3b85670719'],185,Starlink 4-34 (v1.5),2022-09-17T01:05:00.000Z,True,False,28.561857,-80.577366,1663376700,23.6,10.4,95,100,NaN,NaN,NaN,NaN
185,5e9d0d95eda69973a809d1ec,5e9e4501f509094ba4566f84,['631616a7ffc78f3b8567071a'],186,Starlink 4-35 (v1.5),2022-09-24T23:30:00.000Z,True,False,28.561857,-80.577366,1664062200,26.4,16.6,79,17,NaN,NaN,NaN,NaN